### ISSUE TITLE
[Strictly 10.3.0] External S3 1.0.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_external_s3#158]
This is the server app release template, please copy the part below in a new ticket.
For instructions around app releases, see https://handbook.owncloud.com/releasing_apps.html

### Reason

- Initial release
- [x] update AWS lib: https://github.com/owncloud/files_external_s3/issues/159
- [x] config migration #237 
- [ ] TODO: acceptance tests

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "External S3 1.0.0" test Plan @davitol https://github.com/owncloud/files_external_s3/issues/250

### Documentation

- [ ] Changes in the docs needed? - > Release Notes

### Marketing

- [x] Ping @owncloud/marketing
- [x] Check/adapt info.xml stuff https://github.com/owncloud/files_external_s3/pull/160
- [x] Check/adapt screenshot https://github.com/owncloud/files_external_s3/pull/160
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries: https://github.com/owncloud/files_external_s3/releases/tag/v1.0.0RC1
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch @davitol https://github.com/owncloud/files_external_s3/issues/250

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable) @davitol 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [ ] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by PVince81** [comment]
- [ ] update info.xml for marketplace @pmaier1

**Comment by pmaier1** [comment]
Info.xml => https://github.com/owncloud/files_external_s3/pull/160

**Comment by PVince81** [comment]
- [ ] publish to marketplace (create initial entry there)

**Comment by PVince81** [comment]
- [ ] need quick manual test (basic functionality) with both files_primary_s3 and files_external_s3 apps enabled and configured (is there a way to automate ?)

**Comment by PVince81** [comment]
- [ ] fix drone.yml to work with master instead of stable10

**Comment by PVince81** [comment]
- [ ] create makefile
- [ ] create changelog

**Comment by PVince81** [comment]
1.0.0RC1 built here: https://github.com/owncloud/files_external_s3/releases/tag/v1.0.0RC1

@davitol please test.

Also check whether S3 storages setup in 10.2 are available also in 10.3 after upgrading.

**Comment by PVince81** [comment]
Note: min-version of this app is set to 10.3 to make sure it's not mixed up with earlier versions where it was present in core

**Comment by micbar** [comment]
1.0.0RC2 built here: https://github.com/owncloud/files_external_s3/releases/tag/v1.0.0RC2

Includes #232 

@davitol please test.

**Comment by davitol** [comment]
> 1.0.0RC2 built here: https://github.com/owncloud/files_external_s3/releases/tag/v1.0.0RC2

Small detail related to 1.0.0.RC2. Readme.md is included in the tarball, but it has no content

**Comment by micbar** [comment]
@pmaier1 We should not ship with an empty Readme.

@settermjd Could you help out?

**Comment by micbar** [comment]
1.0.0RC3 Build here https://github.com/owncloud/files_external_s3/releases/tag/v1.0.0RC3

@davitol Should also include #237

**Comment by davitol** [comment]
@micbar Tarball is QA-ready. Test results here: https://github.com/owncloud/files_external_s3/issues/250

**TBD**
- [ ] Write Readme.md content
- [ ] Clarify Release notes ? (install and enable app, re-mark checkbox for personal mounts etc)
- [ ] Image for this app in marketplace ?

@pmaier jfyi

**Comment by davitol** [comment]
@pmaier1 

- Upgrade to oC 10.3.0. using tarball (it bundles Files external S3)
- Enable the app via cli (```occ app:enable files external S3```)
- If it was allowed previously personal mount points, then check again that option (see screenshot below)
<img width="426" alt="Screen Shot 2019-09-24 at 16 11 21" src="https://user-images.githubusercontent.com/10596560/65519339-0a68de80-dee6-11e9-839e-2e8ddf9b797d.png">

**Comment by micbar** [comment]
@davitol 
Created Final Tarball https://github.com/owncloud/files_external_s3/releases

Could you smoketest?

**Comment by davitol** [comment]
>     * Readme is only for GH, can stay as is for the release

Readme.md file is included empty in the Final Tarball

@micbar @pmaier1 jfyi

**Comment by davitol** [comment]
Changelog file shows Unreleased as release date

```
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/).

## [Unreleased]

## 1.0.0

- Moved from core into a separate app - [#2](https://github.com/owncloud/files_external_s3/pull/2)
- Updated AWS SDK library to 3.110.3

[Unreleased]: https://github.com/owncloud/files_external_s3/compare/v1.0.0..master
```

@micbar @pmaier1 jfyi

**Comment by davitol** [comment]
The smoke test for files external s3 functionality went fine
