### ISSUE TITLE
Tracking Testing results for Files External S3 1.0.0

### ISSUE THREAD

**Issue by davitol** [owncloud/files_external_s3#250]
- [x] enable app via ```occ app:enable files_external_s3```
- [x] disable app via ```occ app:enable files_external_s3```
- [x] install app from tarball via ```occ market:install -l files_external_s3.tarball```
- [x] Configure a Global mount point as admin
- [x] Configure a personal mount point as regular user
- [x] Upload a file to S3 mount point
- [x] Delete a file from S3 mount point
- [x] Enable sharing in mountpoint and share a file
- [x] Tag file hosted in S3 mountpoint
- [x] Comment a file hosted in S3 mountpoint
- [x] In oC 10.2.1 Configure an S3 External Mount Point (personal and global) and upgrade to oC 10.3 and enable files external 1.0.0. (Check mounts are available)
